```{r}
#install.packages('DBI')
#install.packages("dplyr")
#install.packages("dbplyr")
library(DBI)
library(dplyr)
library(dbplyr)

con <- dbConnect(
  bigrquery::bigquery(),
  project = "physionet-data",
  dataset = "eicu_crd",
  billing = "london-datathon"
)
con 

tbl_list <- dbListTables(con)
tbl_list
#dplyr::tbl(con, "allergy") %>% collect()

```

```{r}

lab_vals <- dplyr::tbl(con, "lab") %>% 
  dplyr::select(labname) %>%
  group_by(labname) %>% 
  summarise(n=n()) %>% collect()

chloride <- dplyr::tbl(con, "lab") %>% 
  dplyr::select(patientunitstayid, labresultrevisedoffset, labname, labresult) %>% filter(labname == 'chloride'
  ) %>% filter(!is.na(labresult) %>% collect() %>% rename(time = labresultrevisedoffset) 
  
  
t2 <- ggplot(chloride, aes(x = labresult)) 
t2 + stat_ecdf()

# we have 350 values , some of which are junk , to get the 99.5% quantiles do

quantile(chloride$labresult, probs = c(0.0005, 1-0.0005))
# which gives => 
# 0.05% 99.95% 
#    71    137 

# clean the 
# - BE / 
# Hco3
# pH


# 

install.packages('stringr')
library(stringr)
base_xs <- dplyr::tbl(con, "lab") %>% 
  dplyr::select(patientunitstayid, labresultrevisedoffset, labname, labresult)%>% filter(labname == 'Base Excess') %>% collect()

base_xs <- filter(base_xs, !is.na(labresult))  %>% 
  rename(time = labresultrevisedoffset) 

base_def <- dplyr::tbl(con, "lab") %>% 
  dplyr::select(patientunitstayid, labresultrevisedoffset, labname, labresult)%>% filter(labname == 'Base Deficit') %>% collect()

base_def <- filter(base_def, !is.na(labresult)) %>% 
 rename(time = labresultrevisedoffset) %>% 
  mutate(labresult = case_when(
    labresult <= 0 ~ labresult,
    labresult > 0 ~ -labresult,
    FALSE ~ NA_real_
  ))
  
base_xs <- bind_rows(base_xs,base_def)

quantile(base_xs$labresult, probs = c(0.005, 1-0.005))
#  0.5% 99.5% 
# -22.8  20.0 

bicarb <- 
  dplyr::tbl(con, "lab") %>% 
  dplyr::select(patientunitstayid, labresultrevisedoffset, labname, labresult)%>% filter(labname == 'bicarbonate') %>% dplyr::select(-labname) %>% collect() 

bicarb <- filter(bicarb, !is.na(labresult))

hco3 <- 
  dplyr::tbl(con, "lab") %>% 
  dplyr::select(patientunitstayid, labresultrevisedoffset, labname, labresult)%>% filter(labname == 'HCO3') %>% dplyr::select(-labname) %>% collect() 

hco3 <- filter(hco3, !is.na(labresult))

bicarb <- bind_rows(bicarb, hco3)
quantile(bicarb$labresult, probs = c(0.005, 0.995))

#0.5% 99.5% 
#8.9  44.0 

# pH

lab_vals %>% filter(str_detect(labname, regex('ph', ignore_case = T)))
# only one lab term for pH

ph <- 
  dplyr::tbl(con, "lab") %>% 
  dplyr::select(patientunitstayid, labresultrevisedoffset, labname, labresult)%>% filter(labname == 'pH') %>% dplyr::select(-labname) %>% collect() 

ph <- filter(ph, !is.na(labresult))
quantile(ph$labresult, probs = c(0.005, 0.995))

# 0.5% 99.5% 
# 6.96  7.59 
```


|             | Lower Filter Limit | Upper Filter Limit |   |
|-------------|--------------------|--------------------|---|
| Chloride    |         71         |         137        |   |
| Base Excess |        -22.8       |         20         |   |
| Bicarbonate |         8.9        |        44.0        |   |
| pH          |        6.96        |        7.59        |   |